site_name: Mikompilation
site_url: https://www.mikompilation.com
site_description: Research project to reimplement Fatal Frame 2
site_author: wagrenier

repo_url: https://github.com/wagrenier/Mikompilation
edit_uri: blob/main/docs

nav:
  - Home: index.md
  - Build: Build.md
  - Engine: 
      - Engine/Engine.md
      - 3D:
        - SGD: Engine/3D/SGD.md
  - Game:
      - GPhaseSytem: Game/GPhaseSystem.md

theme: 
  name: material
  logo: img/angry_noise_sae.png
  favicon: img/favicon.ico
  features:
    - content.code.copy
    - content.code.annotate

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
      linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences

plugins:
  - search