name: Build Mikompilation

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: ${{ matrix.os }} 
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest, macos-latest]

    steps:
    - uses: actions/checkout@v2
    
    - name: Install Dependencies
      if: ${{ matrix.os == 'ubuntu-latest' }}
      run: |
          sudo apt install xorg-dev
          sudo apt install gcc-multilib g++-multilib
          sudo apt update
          sudo apt upgrade
          sudo apt-get install libglx-dev
          sudo apt-get install mesa-common-dev
          sudo apt-get install libglu1-mesa-dev

    - name: Configure CMake
      run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}

    - name: Build
      run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}

    - name: Test
      working-directory: ${{github.workspace}}/build
      run: ctest -C ${{env.BUILD_TYPE}}